CREATE TABLE ACCOUNTS (
	ACCOUNT_NUMBER VARCHAR(12)  PRIMARY KEY,
	USER_ID VARCHAR(50) NOT NULL,
	ACCOUNT_NAME VARCHAR(255) NOT NULL,
	ACCOUNT_TYPE VARCHAR(12) NOT NULL,
	CURRENCY CHAR(3) NOT NULL,
	BALANCE_DATE DATE NOT NULL,
	AVAILABLE_BALANCE NUMERIC(10,2) NOT NULL
);

CREATE TABLE TRANSATIONS (
    TRANS_ID VARCHAR(255) PRIMARY KEY,
	ACCOUNT_NUMBER VARCHAR(12)  NOT NULL,
	VALUE_DATE DATE NOT NULL,
	CURRENCY CHAR(3) NOT NULL,
	AMOUNT NUMERIC(10,2) NOT NULL,
	TRANS_NARRATIVE VARCHAR(255),
	CONSTRAINT FK_ACCOUNT_NUMBER
      FOREIGN KEY(ACCOUNT_NUMBER)
	  REFERENCES ACCOUNTS(ACCOUNT_NUMBER)
);
